export const plans = [
  {
    id: 1,
    name: "Basic",
    price: 19.99,
    annualPrice: 199.99,
    storage: "500 GB",
    usersAllowed: 2,
    sendLimit: "3 GB",
    isRecommended: false,
  },
  {
    id: 2,
    name: "Professional",
    price: 24.99,
    annualPrice: 249.99,
    storage: "1 TB",
    usersAllowed: 5,
    sendLimit: "10 GB",
    isRecommended: true,
  },
  {
    id: 3,
    name: "Master",
    price: 39.99,
    annualPrice: 399.99,
    storage: "2 TB",
    usersAllowed: 10,
    sendLimit: "20 GB",
    isRecommended: false,
  },
];
